services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=com.example.database'
      - 'POSTGRES_PASSWORD=secret_password'
      - 'POSTGRES_USER=com.example.database'
    ports:
      - '5432:5432'